document.addEventListener('DOMContentLoaded', function() {
    const palavras = [
        'Cachorro',
    'Gato',
    'Árvore',
    'Casa',
    'Sol',
    'Lua',
    'Estrela',
    'Flor',
    'Carro',
    'Avião',
    'Barco',
    'Bola',
    'Pato',
    'Elefante',
    'Coelho',
    'Borboleta',
    'Cavalo',
    'Pássaro',
    'Peixe',
    'Sapo',
    'Unicórnio',
    'Dragão',
    'Coroa',
    'Espada',
    'Arco',
    'Flecha',
    'Coração',
    'Estrela do Mar',
    'Cacto',
    'Montanha',
    'Onda',
    'Tartaruga',
    'Dinossauro',
    'Foca',
    'Leão',
    'Tigre',
    'Girafa',
    'Macaco',
    'Cobra',
    'Rato',
    'Abelha',
    'Flamingo',
    'Formiga',
    'Galinha',
    'Elefante',
    'Zebra',
    'Urso',
    'Pinguim',
    'Aranha',
    'Joaninha',
    'Baleia',
    'Ovelha',
    'Gnu',
    'Polvo',
    'Caranguejo',
    'Lagarto',
    'Papagaio',
    'Esfinge',
    'Orc',
    'Fada',
    'Bruxa',
    'Pirata',
    'Robô',
    'Guerreiro',
    'Ninja',
    'Cowboy',
    'Viking',
    'Mago',
    'Cavaleiro',
    'Princesa',
    'Rainha',
    'Rei',
    'Palhaço',
    'Zumbi',
    'Fantasma',
    'Vampiro',
    'Esqueleto',
    'Morcego',
    'Sereia',
    'Policia',
    'Bombeiro',
    'Médico',
    'Enfermeira',
    'Cozinheiro',
    'Padeiro',
    'Garçom',
    'Professor',
    'Estudante',
    'Artista',
    'Músico',
    'Escritor',
    'Cantor',
    'Dançarino',
    'Atleta',
    'Soldado',
    'Marinheiro',
    'Piloto',
    'Astronauta',
    'Carpinteiro',
    'Encanador',
    'Eletricista',
    'Jardineiro',
    'Pintor',
    'Carteiro',
    'Advogado',
    'Juiz',
    'Detetive',
    'Jornalista',
    'Cientista',
    'Engenheiro',
    'Programador',
    'Designer',
    'CEO',
    'Chefe de Cozinha',
    'Gerente',
    'Recepcionista',
    'Secretária',
    'Bebê',
    'Criança',
    'Adolescente',
    'Adulto',
    'Idoso',
    'Bola de Neve',
    'Boneco de Neve',
    'Iglu',
    'Esquilo',
    'Aguia',
    'Abóbora',
    'Fantasia de Halloween',
    'Fogueira',
    'Caneca',
    'Xícara',
    'Prato',
    'Talheres',
    'Panela',
    'Frigideira',
    'Garrafa',
    'Copos',
    'Lanche',
    'Hambúrguer',
    'Pizza',
    'Cachorro-Quente',
    'Sorvete',
    'Bolo',
    'Pão',
    'Croissant',
    'Donut',
    'Frutas',
    'Maçã',
    'Banana',
    'Laranja',
    'Morango',
    'Pera',
    'Uva',
    'Melancia',
    'Abacaxi',
    'Limão',
    'Tomate',
    'Cenoura',
    'Alface',
    'Cebola',
    'Pimentão',
    'Brocólis',
    'Cogumelo',
    'Batata',
    'Brócolis',
    'Espinafre',
    'Milho',
    'Berinjela',
    'Pepino',
    'Melão',
    'Gelo',
    'Fogo',
    'Água',
    'Terra',
    'Ar',
    'Sol',
    'Lua',
    'Estrela',
    'Nuvem',
    'Raio',
    'Arco-Íris',
    'Arco de Flechas',
    'Mapa do Tesouro',
    'Mochila',
    'Óculos',
    'Relógio',
    'Celular',
    'Computador',
    'Teclado',
    'Mouse',
    'Câmera',
    'Fone de Ouvido',
    'Microfone',
    'Caixa de Som',
    'Controle Remoto',
    'Bateria',
    'Carregador',
    'Livro',
    'Revista',
    'Jornal',
    'Diário',
    'Quadro',
    'Estatueta',
    'Vaso',
    'Relógio de Parede',
    'Abajur',
    'Tapete',
    'Almofada',
    'Cortina',
    'Cadeira',
    'Mesa',
    'Sofá',
    'Estante',
    'Cama',
    'Guarda-Roupa',
    'Espelho',
    'Armário',
    'Luminária',
    'Poltrona',
    'Pufe',
    'Lareira',
    'Vaso Sanitário',
    'Pia',
    'Banheira',
    'Chuveiro',
    'Toalha',
    'Sabonete',
    'Shampoo',
    'Condicionador',
    'Escova de Dentes',
    'Pasta de Dentes',
    'Fio Dental',
    'Desodorante',
    'Perfume',
    'Secador de Cabelo',
    'Pente',
    'Alicate de Unha',
    'Esmalte',
    'Lixa de Unha',
    'Tesoura',
    'Escova de Cabelo',
    'Babador',
    'Fralda',
    'Chupeta',
    'Mamadeira',
    'Carrinho de Bebê',
    'Berço',
    'Andador',
    'Jogos de Tabuleiro',
    'Quebra-Cabeça',
    'Damas',
    'Xadrez',
    'Dominó',
    'Casa de Bonecas',
    'Carrinho de Brinquedo',
    'Urso de Pelúcia',
    'Boneca',
    'Bicicleta',
    'Patins',
    'Skate',
    'Bola',
    'Raquete de Tênis',
    'Raquete de Ping Pong',
    'Luvas de Boxe',
    'Saco de Pancadas',
    'Trampolim',
    'Pula-Pula',
    'Corda de Pular',
    'Frisbee',
    'Kite',
    'Peteca',
    'Bumerangue',
        // Adicione todas as palavras aqui
    ];

    const sortearAzulBtn = document.getElementById('sortearAzul');
    const sortearVerdeBtn = document.getElementById('sortearVerde');
    const mostrarAzulBtn = document.getElementById('mostrarAzul');
    const mostrarVerdeBtn = document.getElementById('mostrarVerde');
    const resetarBtn = document.getElementById('resetar');
    const palavraAzulDiv = document.getElementById('palavraAzul');
    const palavraVerdeDiv = document.getElementById('palavraVerde');

    sortearAzulBtn.addEventListener('click', function() {
        const palavra = sortearPalavra();
        localStorage.setItem('palavraAzul', palavra);
    });

    sortearVerdeBtn.addEventListener('click', function() {
        const palavra = sortearPalavra();
        localStorage.setItem('palavraVerde', palavra);
    });

    mostrarAzulBtn.addEventListener('click', function() {
        const palavra = localStorage.getItem('palavraAzul');
        if (palavra) {
            palavraAzulDiv.innerText = palavra;
            palavraAzulDiv.style.display = palavraAzulDiv.style.display === 'none' ? 'block' : 'none';
        }
    });

    mostrarVerdeBtn.addEventListener('click', function() {
        const palavra = localStorage.getItem('palavraVerde');
        if (palavra) {
            palavraVerdeDiv.innerText = palavra;
            palavraVerdeDiv.style.display = palavraVerdeDiv.style.display === 'none' ? 'block' : 'none';
        }
    });

    resetarBtn.addEventListener('click', function() {
        localStorage.removeItem('palavraAzul');
        localStorage.removeItem('palavraVerde');
        palavraAzulDiv.style.display = 'none';
        palavraVerdeDiv.style.display = 'none';
    });

    function sortearPalavra() {
        const index = Math.floor(Math.random() * palavras.length);
        return palavras[index];
    }
});